# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1529d9a36567e24dd884a907135764bd76f8599c813f179e16eef07b71d73e14a864d680993dc4f606e4e46c8ffd48b1a26db7ce1b1915aeffbedb132f8f29

test:
  secret_key_base: ca6c4c2e8e2fc0be373e62f24ac834253743c7f362f4011848aa21169b06bab4ee4e849f9fd88cfad9f1b6f86bbabc3413dd95ed9112c075154c257df389efad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
